/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import com.sun.opengl.util.Animator;
import Animaciones.AnimacionEnder;
import Animaciones.AnimacionPolarin;
import Animaciones.AnimacionNieves;
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class MenuSeleccionPersonaje extends javax.swing.JFrame {

    private final Animator animatorPolarin;
    private final Animator animatorNieves;
    private final Animator animatorEnder;

    public static Clip clipFondo;

    AnimacionPolarin polarin = new AnimacionPolarin();
    AnimacionNieves nieves = new AnimacionNieves();
    AnimacionEnder ender = new AnimacionEnder();

    /**
     * Creates new form MenuSeleccionPersonaje
     */
    public MenuSeleccionPersonaje() {
        initComponents();
        this.setLocationRelativeTo(null);

        canvasPolarin.addGLEventListener(polarin);
        animatorPolarin = new Animator(canvasPolarin);
        animatorPolarin.start();

        canvasNieves.addGLEventListener(nieves);
        animatorNieves = new Animator(canvasNieves);
        animatorNieves.start();

        canvasEnder.addGLEventListener(ender);
        animatorEnder = new Animator(canvasEnder);
        animatorEnder.start();

        panelDescripcionPolarin.setVisible(false);
        panelDescripcionMagno.setVisible(false);
        panelDescripcionEnder.setVisible(false);

        sonidoFondo("sonido_menu");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelDescripcionPolarin = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panelCanvasPolarin = new javax.swing.JPanel();
        canvasPolarin = new javax.media.opengl.GLCanvas();
        panelDescripcionMagno = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelCanvasMagno = new javax.swing.JPanel();
        canvasNieves = new javax.media.opengl.GLCanvas();
        panelDescripcionEnder = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelCanvasEnder = new javax.swing.JPanel();
        canvasEnder = new javax.media.opengl.GLCanvas();
        btnSelectPolarin = new javax.swing.JButton();
        btnSelectNieves = new javax.swing.JButton();
        btnSelectEnder = new javax.swing.JButton();
        jBSonidoOff = new javax.swing.JToggleButton();
        jBSonidoOn = new javax.swing.JToggleButton();
        comboBoxEnder = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelAreaPolarin = new javax.swing.JPanel();
        jPanelAreaMagno = new javax.swing.JPanel();
        jPanelAreaEnder = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        panelDescripcionPolarin1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        panelDescripcionPolarin2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(java.awt.Color.red);
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Selecciona tu personaje:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 70));

        panelDescripcionPolarin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel3.setText("Polarin:");

        jLabel7.setText("Personaje timido.");

        jLabel8.setText("PowerUp: Disminuir su tamaño por 4 segundos. ");

        jLabel9.setText("Debilidad: Lentitud al activar poder especial.");

        javax.swing.GroupLayout panelDescripcionPolarinLayout = new javax.swing.GroupLayout(panelDescripcionPolarin);
        panelDescripcionPolarin.setLayout(panelDescripcionPolarinLayout);
        panelDescripcionPolarinLayout.setHorizontalGroup(
            panelDescripcionPolarinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescripcionPolarinLayout.createSequentialGroup()
                .addGroup(panelDescripcionPolarinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDescripcionPolarinLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelDescripcionPolarinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDescripcionPolarinLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDescripcionPolarinLayout.setVerticalGroup(
            panelDescripcionPolarinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescripcionPolarinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelDescripcionPolarin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 240, 170));

        panelCanvasPolarin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout panelCanvasPolarinLayout = new javax.swing.GroupLayout(panelCanvasPolarin);
        panelCanvasPolarin.setLayout(panelCanvasPolarinLayout);
        panelCanvasPolarinLayout.setHorizontalGroup(
            panelCanvasPolarinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvasPolarin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelCanvasPolarinLayout.setVerticalGroup(
            panelCanvasPolarinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvasPolarin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(panelCanvasPolarin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 290, 230));

        panelDescripcionMagno.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel4.setText("Magno:");

        javax.swing.GroupLayout panelDescripcionMagnoLayout = new javax.swing.GroupLayout(panelDescripcionMagno);
        panelDescripcionMagno.setLayout(panelDescripcionMagnoLayout);
        panelDescripcionMagnoLayout.setHorizontalGroup(
            panelDescripcionMagnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescripcionMagnoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDescripcionMagnoLayout.setVerticalGroup(
            panelDescripcionMagnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescripcionMagnoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelDescripcionMagno, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 240, 170));

        panelCanvasMagno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout panelCanvasMagnoLayout = new javax.swing.GroupLayout(panelCanvasMagno);
        panelCanvasMagno.setLayout(panelCanvasMagnoLayout);
        panelCanvasMagnoLayout.setHorizontalGroup(
            panelCanvasMagnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCanvasMagnoLayout.createSequentialGroup()
                .addComponent(canvasNieves, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelCanvasMagnoLayout.setVerticalGroup(
            panelCanvasMagnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvasNieves, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(panelCanvasMagno, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 290, 230));

        panelDescripcionEnder.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel5.setText("Ender:");

        javax.swing.GroupLayout panelDescripcionEnderLayout = new javax.swing.GroupLayout(panelDescripcionEnder);
        panelDescripcionEnder.setLayout(panelDescripcionEnderLayout);
        panelDescripcionEnderLayout.setHorizontalGroup(
            panelDescripcionEnderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescripcionEnderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDescripcionEnderLayout.setVerticalGroup(
            panelDescripcionEnderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescripcionEnderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelDescripcionEnder, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 360, 240, 170));

        panelCanvasEnder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout panelCanvasEnderLayout = new javax.swing.GroupLayout(panelCanvasEnder);
        panelCanvasEnder.setLayout(panelCanvasEnderLayout);
        panelCanvasEnderLayout.setHorizontalGroup(
            panelCanvasEnderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCanvasEnderLayout.createSequentialGroup()
                .addComponent(canvasEnder, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelCanvasEnderLayout.setVerticalGroup(
            panelCanvasEnderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvasEnder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(panelCanvasEnder, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 160, 300, 230));

        btnSelectPolarin.setBackground(new java.awt.Color(255, 0, 0));
        btnSelectPolarin.setText("Seleccionar");
        btnSelectPolarin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSelectPolarinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSelectPolarinMouseExited(evt);
            }
        });
        btnSelectPolarin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectPolarinActionPerformed(evt);
            }
        });
        jPanel1.add(btnSelectPolarin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 110, 40));

        btnSelectNieves.setBackground(new java.awt.Color(255, 0, 0));
        btnSelectNieves.setText("Seleccionar");
        btnSelectNieves.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSelectNievesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSelectNievesMouseExited(evt);
            }
        });
        btnSelectNieves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectNievesActionPerformed(evt);
            }
        });
        jPanel1.add(btnSelectNieves, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 530, 110, 40));

        btnSelectEnder.setBackground(new java.awt.Color(255, 0, 0));
        btnSelectEnder.setText("Seleccionar");
        btnSelectEnder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSelectEnderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSelectEnderMouseExited(evt);
            }
        });
        btnSelectEnder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectEnderActionPerformed(evt);
            }
        });
        jPanel1.add(btnSelectEnder, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 530, 120, 40));

        jBSonidoOff.setText("Off");
        jBSonidoOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSonidoOffActionPerformed(evt);
            }
        });
        jPanel1.add(jBSonidoOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 730, -1, -1));

        jBSonidoOn.setSelected(true);
        jBSonidoOn.setText("On");
        jBSonidoOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSonidoOnActionPerformed(evt);
            }
        });
        jPanel1.add(jBSonidoOn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 730, -1, -1));

        comboBoxEnder.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Expesion:", "Feliz", "Triste", "Sexy", "Enojado", "Sorprendido" }));
        comboBoxEnder.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxEnderItemStateChanged(evt);
            }
        });
        comboBoxEnder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxEnderActionPerformed(evt);
            }
        });
        jPanel1.add(comboBoxEnder, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 450, 100, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sonido:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 730, 50, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/GameboyFondo.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1362, 726));
        jLabel1.setMinimumSize(new java.awt.Dimension(1362, 726));
        jLabel1.setPreferredSize(new java.awt.Dimension(1362, 726));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));
        jLabel1.getAccessibleContext().setAccessibleParent(jLabel1);

        jPanelAreaPolarin.setBackground(new java.awt.Color(0,0,0,10));
        jPanelAreaPolarin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAreaPolarinMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanelAreaPolarinLayout = new javax.swing.GroupLayout(jPanelAreaPolarin);
        jPanelAreaPolarin.setLayout(jPanelAreaPolarinLayout);
        jPanelAreaPolarinLayout.setHorizontalGroup(
            jPanelAreaPolarinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelAreaPolarinLayout.setVerticalGroup(
            jPanelAreaPolarinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanelAreaPolarin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 450, 710));

        jPanelAreaMagno.setBackground(new java.awt.Color(0,0,0,10));
        jPanelAreaMagno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAreaMagnoMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanelAreaMagnoLayout = new javax.swing.GroupLayout(jPanelAreaMagno);
        jPanelAreaMagno.setLayout(jPanelAreaMagnoLayout);
        jPanelAreaMagnoLayout.setHorizontalGroup(
            jPanelAreaMagnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelAreaMagnoLayout.setVerticalGroup(
            jPanelAreaMagnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanelAreaMagno, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 440, 700));

        jPanelAreaEnder.setBackground(new java.awt.Color(0,0,0,10));
        jPanelAreaEnder.setMaximumSize(new java.awt.Dimension(1370, 727));
        jPanelAreaEnder.setPreferredSize(new java.awt.Dimension(1370, 727));
        jPanelAreaEnder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAreaEnderMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanelAreaEnderLayout = new javax.swing.GroupLayout(jPanelAreaEnder);
        jPanelAreaEnder.setLayout(jPanelAreaEnderLayout);
        jPanelAreaEnderLayout.setHorizontalGroup(
            jPanelAreaEnderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelAreaEnderLayout.setVerticalGroup(
            jPanelAreaEnderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanelAreaEnder, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 70, 440, 727));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Expesion:", "Enojado", "Triste", "Feliz ", "Mareado" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 100, -1));

        panelDescripcionPolarin1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel10.setText("Polarin:");

        jLabel11.setText("Personaje timido.");

        jLabel12.setText("PowerUp: Disminuir su tamaño por 4 segundos. ");

        jLabel13.setText("Debilidad: Lentitud al activar poder especial.");

        javax.swing.GroupLayout panelDescripcionPolarin1Layout = new javax.swing.GroupLayout(panelDescripcionPolarin1);
        panelDescripcionPolarin1.setLayout(panelDescripcionPolarin1Layout);
        panelDescripcionPolarin1Layout.setHorizontalGroup(
            panelDescripcionPolarin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescripcionPolarin1Layout.createSequentialGroup()
                .addGroup(panelDescripcionPolarin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDescripcionPolarin1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelDescripcionPolarin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDescripcionPolarin1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDescripcionPolarin1Layout.setVerticalGroup(
            panelDescripcionPolarin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescripcionPolarin1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelDescripcionPolarin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 240, 170));

        panelDescripcionPolarin2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel14.setText("Polarin:");

        jLabel15.setText("Personaje timido.");

        jLabel16.setText("PowerUp: Disminuir su tamaño por 4 segundos. ");

        jLabel17.setText("Debilidad: Lentitud al activar poder especial.");

        javax.swing.GroupLayout panelDescripcionPolarin2Layout = new javax.swing.GroupLayout(panelDescripcionPolarin2);
        panelDescripcionPolarin2.setLayout(panelDescripcionPolarin2Layout);
        panelDescripcionPolarin2Layout.setHorizontalGroup(
            panelDescripcionPolarin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescripcionPolarin2Layout.createSequentialGroup()
                .addGroup(panelDescripcionPolarin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDescripcionPolarin2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelDescripcionPolarin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDescripcionPolarin2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDescripcionPolarin2Layout.setVerticalGroup(
            panelDescripcionPolarin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescripcionPolarin2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelDescripcionPolarin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 240, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelAreaPolarinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAreaPolarinMouseEntered
        // TODO add your handling code here:
        this.pauseAnimations();
        polarin.setBndAnimacion(true);
    }//GEN-LAST:event_jPanelAreaPolarinMouseEntered

    private void jPanelAreaMagnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAreaMagnoMouseEntered
        // TODO add your handling code here:
        this.pauseAnimations();
        nieves.setBndAnimacion(true);
    }//GEN-LAST:event_jPanelAreaMagnoMouseEntered

    private void jPanelAreaEnderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAreaEnderMouseEntered
        // TODO add your handling code here:
        this.pauseAnimations();
        ender.setBndAnimacion(true);
    }//GEN-LAST:event_jPanelAreaEnderMouseEntered

    private void btnSelectNievesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectNievesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnSelectNievesActionPerformed

    private void btnSelectPolarinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectPolarinActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnSelectPolarinActionPerformed

    private void btnSelectEnderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectEnderActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnSelectEnderActionPerformed

    private void btnSelectPolarinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectPolarinMouseEntered
        // TODO add your handling code here:
        panelDescripcionPolarin.setVisible(true);
    }//GEN-LAST:event_btnSelectPolarinMouseEntered

    private void btnSelectPolarinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectPolarinMouseExited
        // TODO add your handling code here:
        panelDescripcionPolarin.setVisible(false);
    }//GEN-LAST:event_btnSelectPolarinMouseExited

    private void btnSelectNievesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectNievesMouseEntered
        // TODO add your handling code here:
        panelDescripcionMagno.setVisible(true);
    }//GEN-LAST:event_btnSelectNievesMouseEntered

    private void btnSelectNievesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectNievesMouseExited
        // TODO add your handling code here:
        panelDescripcionMagno.setVisible(false);
    }//GEN-LAST:event_btnSelectNievesMouseExited

    private void btnSelectEnderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectEnderMouseEntered
        // TODO add your handling code here:
        panelDescripcionEnder.setVisible(true);

    }//GEN-LAST:event_btnSelectEnderMouseEntered

    private void btnSelectEnderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectEnderMouseExited
        // TODO add your handling code here:
        panelDescripcionEnder.setVisible(false);
    }//GEN-LAST:event_btnSelectEnderMouseExited

    private void jBSonidoOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSonidoOffActionPerformed
        clipFondo.stop();
    }//GEN-LAST:event_jBSonidoOffActionPerformed

    private void jBSonidoOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSonidoOnActionPerformed
        if (!clipFondo.isRunning()) {
            clipFondo.start();

        }
    }//GEN-LAST:event_jBSonidoOnActionPerformed

    private void comboBoxEnderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxEnderActionPerformed
        // boolean[] acciones;TODO add your handling code here:
        boolean[] acciones = {false, false, false, false, false, false, false, false, false, false};

        switch (this.comboBoxEnder.getSelectedIndex()) {

            case 1:
                acciones[5] = true;
                break;
            case 2:
                acciones[6] = true;
                break;
            case 3:
                acciones[7] = true;
                break;
            case 4:
                acciones[8] = true;
                break;
            case 5:
                acciones[9] = true;
                break;

        }
        ender.setAnimaciones(acciones);
    }//GEN-LAST:event_comboBoxEnderActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void comboBoxEnderItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxEnderItemStateChanged
        // TODO add your handling code here:
//        switch(this.comboBoxEnder.getSelectedIndex()){
//            case 1:
//                boolean[] acciones = {false, true, false, false, false, true, false, false, false, false};
//                ender.setAnimaciones(acciones);
//                break;
//        }

    }//GEN-LAST:event_comboBoxEnderItemStateChanged

    public void pauseAnimations() {

        ender.setBndAnimacion(false);
        ender.setAnimaciones(false);
        nieves.setBndAnimacion(false);
        polarin.setBndAnimacion(false);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSeleccionPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSeleccionPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSeleccionPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSeleccionPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuSeleccionPersonaje().setVisible(true);
            }
        });
    }

    public static synchronized void sonidoFondo(final String sonido) {
        new Thread(new Runnable() {
            // The wrapper thread is unnecessary, unless it blocks on the
            // Clip finishing; see comments.
            public void run() {
                File d = new File("src/sonidos/sonido_menu.wav");
                try {
                    clipFondo = AudioSystem.getClip();
                    AudioInputStream inputStream = AudioSystem.getAudioInputStream(d);
                    clipFondo.open(inputStream);
                    clipFondo.start();
                } catch (Exception e) {
                    System.err.println(e.getMessage());
                }
            }
        }).start();
    }

    public static synchronized void animacionBorde(boolean state) {
        new Thread(new Runnable() {
            public void run() {
                if (state) {
                    try {
                        this.wait(10000000);
                    } catch (Exception e) {
                        
                    }
                }
            }
        }).start();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelectEnder;
    private javax.swing.JButton btnSelectNieves;
    private javax.swing.JButton btnSelectPolarin;
    private javax.media.opengl.GLCanvas canvasEnder;
    private javax.media.opengl.GLCanvas canvasNieves;
    private javax.media.opengl.GLCanvas canvasPolarin;
    private javax.swing.JComboBox<String> comboBoxEnder;
    private javax.swing.JToggleButton jBSonidoOff;
    private javax.swing.JToggleButton jBSonidoOn;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAreaEnder;
    private javax.swing.JPanel jPanelAreaMagno;
    private javax.swing.JPanel jPanelAreaPolarin;
    private javax.swing.JPanel panelCanvasEnder;
    private javax.swing.JPanel panelCanvasMagno;
    private javax.swing.JPanel panelCanvasPolarin;
    private javax.swing.JPanel panelDescripcionEnder;
    private javax.swing.JPanel panelDescripcionMagno;
    private javax.swing.JPanel panelDescripcionPolarin;
    private javax.swing.JPanel panelDescripcionPolarin1;
    private javax.swing.JPanel panelDescripcionPolarin2;
    // End of variables declaration//GEN-END:variables
}
